title: Gil's Observations
email: nohtaegil@gmail.com
description: >-
  Personal homepage of Dr. Tae-Gil Noh.
  Machine Learning Engineer at OMQ GmbH, based in Berlin.
  A blog about my observations around this evolving world.
url: "https://gilnoh.github.io"
twitter_username: tailblues
github_username: gilnoh
theme: minima
