# title and email
title: "Dr. Tae-Gil Noh | Gil's Observations"
email: nohtaegil@gmail.com

# description
description: >-
  Personal homepage of Tae-Gil Noh (Gil Noh).
  Observations on NLP, AI, and this evolving world.

url: "https://gilnoh.github.io"
twitter_username: tailblues
github_username: gilnoh

# theme
theme: minima

# plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
